spring:
  profiles:
    server:
      port: 8080
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/code?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 789556
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  redis:
    host: localhost
    port: 6379
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mvc:
      view:
        prefix: /
        suffix: .html
